name: Prepare Release

on:
  schedule:
  - cron: "0 0 * * MON,WED,FRI,SUN"
 #   displayName: Four day a week build
 #   branches:
 #       include:
 #       - master
 #   paths-ignore:
 #     - 'package.json'
 #    - 'CHANGELOG.md'
 
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.github_token }}
        # pulls all commits (needed for lerna / semantic release to correctly version)
        fetch-depth: "0"

     # pulls all tags (needed for lerna / semantic release to correctly version)
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*  

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        release-count: '5'
        preset: 'angular'
        skip-on-empty: 'true'
        tag-prefix: ''

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
          
          
